services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./requirements/nginx/html:/var/www/html
    networks:
      - inception

networks:
  inception:
    driver: bridge
