services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/wordpress
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: always
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception

  # BONUS
  redis:
    build: ./requirements/bonus/redis/
    container_name: redis
    restart: always
    networks:
      - inception

  ftp:
    build: ./requirements/bonus/ftp/
    container_name: ftp
    restart: always
    ports:
      - "21:21"
      - "21000-21100:21000-21100"
    volumes:
      - wordpress_volume:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception

# volume 42: /home/ltheveni/data/mysql avec la cmd : mdkir -p /home/ltheveni/data/mysql : pareil pour nginx_volume
volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /tmp/ltheveni/data/wordpress
      o: bind
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /tmp/ltheveni/data/mysql
      o: bind

networks:
  inception:
    name: inception
