services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/html:/var/www/html
    networks:
      - inception

networks:
  inception:
    driver: bridge
